add patch déploiement

diff --git a/.github/workflows/deployTocPanel.yml b/.github/workflows/deployTocPanel.yml
--- a/.github/workflows/deployTocPanel.yml
+++ b/.github/workflows/deployTocPanel.yml
@@ -18,6 +18,13 @@ jobs:
           npm install --save-dev eslint prettier stylelint stylelint-config-standard
           npm run lint
           npm run format
+
+          if [ $? -eq 0 ]
+          then
+            echo "Code verification passed"
+          else
+            echo "Code verification failed"
+          fi
       
       - name: 📂 Sync files
         uses: SamKirkland/FTP-Deploy-Action@4.3.3
@@ -25,7 +32,3 @@ jobs:
           server: ${{ secrets.FTP_SERVER }}
           username: ${{ secrets.FTP_USERNAME }}
           password: ${{ secrets.FTP_PASSWORD }}
-          args: --exclude=".git*"
-          local-dir: dist
-          remote-dir: /public_html
-          delete: 'true'
